version: '3'

services:
  nginx-gitopscompose:
    image: ddeeh/composegitops:3dd6d4f21fa6507dc10db10454b2f3a2335ab0c6
    ports:
      - "80:80"
    command: [ "nginx", "-g", "daemon off;" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3