version: '3'

services:
  nginx-gitopscompose:
    image: ddeeh/composegitops:c9402129056991ae01ebc79bbd57ac7f5af07b19
    ports:
      - "80:80"
    command: [ "nginx", "-g", "daemon off;" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3