version: '3'

services:
  nginx-gitopscompose:
    image: ddeeh/composegitops:2212f0555576a787af4c0ca9200111d5f938b41e
    ports:
      - "80:80"
    restart: always
    command: [ "nginx", "-g", "daemon off;" ]
