version: '3'

services:
  nginx-gitopscompose:
    image: ddeeh/composegitops:bd79d1c72507310c0ba711cfc1020bc5e85e7cac
    ports:
      - "80:80"
    command: [ "nginx", "-g", "daemon off;" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3