name: Release Docker Compose Project

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - '.github/workflows/main.yml'
      - 'Dockerfile'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ddeeh/composegitops:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Update image tag in docker-compose.yml
        run: python3 update_docker_compose.py ${{ github.sha }} ddeeh/composegitops

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docker-compose.yml'
          message: Update Docker Compose image tag to ${{ github.sha }}
